import { Button } from "@/components/ui/button";
import { UserButton } from "@clerk/nextjs";
import Image from "next/image";
import DashboardHeader from "./dashboard/_components/DashboardHeader";
import Footer from "./dashboard/_components/Footer";

export default function Home() {
  return (
    <div>
      <DashboardHeader />

      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 to-white py-24 relative overflow-hidden">
        <div className="absolute top-[-100px] left-[-100px] w-[300px] h-[300px] bg-blue-200 rounded-full opacity-20 animate-pulse" />
        <div className="absolute bottom-[-100px] right-[-100px] w-[300px] h-[300px] bg-indigo-200 rounded-full opacity-20 animate-pulse" />

        <div className="relative z-10 px-6 mx-auto max-w-7xl text-center">
          <h1 className="text-5xl md:text-6xl font-extrabold leading-tight text-gray-900">
            Supercharge Your <span className="text-primary">Exam Prep</span>
          </h1>
          <p className="mt-6 text-lg text-gray-600 md:text-xl max-w-2xl mx-auto">
            Generate AI-powered flashcards, notes, quizzes, and more — all tailored to your syllabus. Smart learning begins here.
          </p>
          <div className="mt-10 flex flex-col sm:flex-row justify-center gap-4">
            <a
              href="/dashboard"
              className="inline-flex items-center justify-center px-6 py-3 text-white bg-primary rounded-lg shadow-lg hover:bg-primary/90 transition"
            >
              🚀 Get Started
            </a>
          </div>

          <div className="mt-16">
            <Image
              src="/dash.png"
              alt="AI Dashboard Preview"
              width={1000}
              height={600}
              className="rounded-xl border shadow-xl mx-auto hover:scale-105 transition-transform"
            />
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white border-t">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <h2 className="text-4xl font-bold text-gray-800 mb-12">
            Why Choose <span className="text-primary">PromptEd AI</span>?
          </h2>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-10">
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                ⚡ Instant Study Material
              </h3>
              <p className="text-gray-600">
                Upload your syllabus or topics and get detailed notes, flashcards, and MCQs instantly generated by AI.
              </p>
            </div>
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                🔁 Smart Revision Tools
              </h3>
              <p className="text-gray-600">
                Use spaced repetition, quick tests, and practice modes to revise smarter, not harder.
              </p>
            </div>
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                📊 Progress Tracking
              </h3>
              <p className="text-gray-600">
                Visualize your strengths and weaknesses with progress charts and AI insights into your learning patterns.
              </p>
            </div>
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                ✍️ Personalized Notes
              </h3>
              <p className="text-gray-600">
                Generate detailed, structured notes with summaries and markdown support tailored to your course.
              </p>
            </div>
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                🎯 Quiz Generator
              </h3>
              <p className="text-gray-600">
                Auto-generate quizzes for each topic with instant feedback and explanations.
              </p>
            </div>
            <div className="p-6 border rounded-xl shadow-sm hover:shadow-md transition">
              <h3 className="text-xl font-semibold text-primary mb-2">
                🌐 Anywhere, Anytime
              </h3>
              <p className="text-gray-600">
                Cloud-based and device-friendly. Study from your laptop, tablet, or mobile — on the go.
              </p>
            </div>
          </div>
        </div>
      </section>

       <Footer /> 
    </div>
  );
}
